fix: tag version

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -66,7 +66,12 @@ jobs:
         id: tagVersion
         # Check if one of the commits is associated with a tag
         run: |
-          echo "tagVersion=$( git tag --merged ${{ github.sha  }} --no-merged ${{ github.event.before }} | grep v*)" >>$GITHUB_OUTPUT
+          TAG=$(git tag --merged ${{ github.sha }} --no-merged ${{ github.event.before }} | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' || echo "invalid")
+          if [ "$TAG" != "invalid" ]; then
+            echo "tagVersion=${TAG}" >>$GITHUB_OUTPUT
+          else
+            echo "tagVersion=none" >>$GITHUB_OUTPUT
+          fi
 
   deploy-to-openshift-development:
     runs-on: ubuntu-latest
